### ISSUE TITLE
Support parentheses

### ISSUE THREAD

**Issue by tadatuta** [tadatuta/bemmet#2]
`b1>(e1{content of e1}+.e2{content of e2})*2`

**Comment by tadatuta** [comment]
Implemented in https://github.com/tadatuta/bemmet/commit/04395a38122e2ff1948425d73e3b5ed8326cf632

**Comment by igoradamenko** [comment]
But if I use parentheses I don't want to use `>`. It's unnecessary. I can construct a tree without `>`, using only `(` & `)`.

`b1(__e1{content}+__e2{content})*2` right now expands to 

```
[
    {
        elem: 'e1',
        content: 'content'
    },
    {
        elem: 'e2',
        content: 'content'
    },
    {
        elem: 'e1',
        content: 'content'
    },
    {
        elem: 'e2',
        content: 'content'
    }
]
```

**Comment by tadatuta** [comment]
@igoradamenko sounds reasonable, created new issue about it: https://github.com/tadatuta/bemmet/issues/6

Thank you for report!
