### ISSUE TITLE
Support parentheses

### ISSUE THREAD

**Issue by blond** [tadatuta/bemmet#4]
Often BEMJSON files wrap in code parentheses to eval code.

``` js
(page)
```

After processing you get error message:

```
Uncaught TypeError: Cannot read property 'modName' of undefined
```

**Expected**

``` js
({
    block: 'page',
    content: {}
})
```

**Comment by tadatuta** [comment]
I'll suggest a workaround:
1. Type `page`
2. Press hotkey to run `bemmet`
3. Press `cmd` + a
4. Press `(`
5. ...
6. PROFIT!!!

**Comment by blond** [comment]
`bemmet` should not throw an error.

And 6 action — too much for a tool that reduces the number of actions ;)

**Comment by tadatuta** [comment]
well I agree that it's not good and should be fixed but that's not something urgent
